name: Bug Report
description: Report a bug or issue with TrustPin iOS SDK
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: input
    id: version
    attributes:
      label: TrustPin SDK Version
      description: What version of TrustPin iOS SDK are you using?
      placeholder: e.g., 0.12.0
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you experiencing the issue on?
      options:
        - iOS
        - macOS
        - watchOS
        - tvOS
        - Mac Catalyst
    validations:
      required: true

  - type: input
    id: ios-version
    attributes:
      label: Platform Version
      description: What version of the platform are you using?
      placeholder: e.g., iOS 17.0, macOS 14.0
    validations:
      required: true

  - type: input
    id: xcode-version
    attributes:
      label: Xcode Version
      description: What version of Xcode are you using?
      placeholder: e.g., 15.0
    validations:
      required: true

  - type: dropdown
    id: pinning-mode
    attributes:
      label: TrustPin Mode
      description: Which pinning mode are you using?
      options:
        - .strict
        - .permissive
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Setup TrustPin with...
        2. Make a request to...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages/Logs
      description: If applicable, add error messages or logs. Please enable debug logging with `await TrustPin.set(logLevel: .debug)`
      render: shell

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample that reproduces the issue
      render: swift

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (network configuration, device specifics, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have enabled debug logging and included relevant logs
          required: false
        - label: I have tested with the latest version of TrustPin
          required: true
        - label: I have checked that my credentials (organization ID, project ID, public key) are correct
          required: true