blank_issues_enabled: false
contact_links:
  - name: TrustPin Documentation
    url: https://trustpin-cloud.github.io/TrustPin-Swift/
    about: Check our comprehensive API documentation
  - name: TrustPin Dashboard
    url: https://app.trustpin.cloud
    about: Manage your certificates and configurations
  - name: Security Issues
    url: mailto:security@trustpin.cloud
    about: Report security vulnerabilities privately
  - name: Support
    url: mailto:support@trustpin.cloud
    about: Contact our support team for urgent issues