name: Question
description: Ask a question about TrustPin iOS SDK usage
title: "[QUESTION] "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using TrustPin? We're here to help! Please check our [documentation](https://trustpin-cloud.github.io/TrustPin-Swift/) first.

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - Setup/Configuration
        - Integration (URLSession, Alamofire, etc.)
        - Error Handling
        - Best Practices
        - Performance
        - Security
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your use case, setup, or what you've tried so far.
      placeholder: |
        I'm trying to...
        I've already tried...
        My setup includes...

  - type: input
    id: version
    attributes:
      label: TrustPin SDK Version
      description: What version of TrustPin iOS SDK are you using?
      placeholder: e.g., 0.12.0

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you working with?
      options:
        - iOS
        - macOS
        - watchOS
        - tvOS
        - Mac Catalyst
        - Multiple platforms
        - Not platform-specific

  - type: textarea
    id: code-sample
    attributes:
      label: Relevant Code (Optional)
      description: If applicable, share relevant code snippets
      render: swift

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the documentation and README
          required: true
        - label: I have searched existing issues for similar questions
          required: true